matrix:
  include:
#    - os: linux
#      language: java
#      jdk: openjdk12
#
#      env:
#        KBUILD=linux
#        JAVA_OPTS=-Xmx2g
#      #skip ./gradlew assemble that is normally invoked in installation step
#      install:
#        - sudo apt-get update
#        - sudo apt-get -y install automake
#      script:
#        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./linuxBuild.sh; fi'
#        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./linuxBuildAndPublish.sh; fi'
    #   OSX macos/ios
    - os: osx
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-mac-ios.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-mac-ios.sh; fi'
    #   OSX watchos
    - os: osx
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-watchos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-watchos.sh; fi'
    #   OSX tvos
    - os: osx
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-tvos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-tvos.sh; fi'
    #   OSX pure
    - os: osx
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-pure.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-pure.sh; fi'
#    - os: windows
#      language: shell
#      jdk: openjdk12
#      env:
#        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
#        - JAVA_OPTS=-Xmx2g
#        - JDK="adopt-openj9@1.11"
#      before_install:
#        - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
#        - source ~/.install-jdk-travis.sh
#      script:
#        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew build ; fi'
#        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew build publishMingwx64PublicationToSnapshotRepository; fi'
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
    - $HOME/.konan/dependencies
branches:
  only:
    - master
