matrix:
  include:
    - os: linux
      name: linux
      language: java
      jdk: openjdk12

      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      #skip ./gradlew assemble that is normally invoked in installation step
      install:
        - sudo apt-get update
        - sudo apt-get -y install automake
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./linuxBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./linuxBuildAndPublish.sh; fi'
    # OSX macos
    - os: osx
      name: osx-mac
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-mac.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-mac.sh; fi'
    # OSX ios
    - os: osx
      name: osx-ios
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-ios.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-ios.sh; fi'
    #   OSX watchos
    - os: osx
      name: osx-watchos
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-watchos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-watchos.sh; fi'
    #   OSX tvos
    - os: osx
      name: osx-tvos
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-tvos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-tvos.sh; fi'

    # OSX macos PURE
    - os: osx
      name: osx-mac-pure
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-pure-mac.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-pure-mac.sh; fi'
    # OSX ios PURE
    - os: osx
      name: osx-ios-pure
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-pure-ios.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-pure-ios.sh; fi'
    #   OSX watchos PURE
    - os: osx
      name: osx-watchos-pure
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-pure-watchos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-pure-watchos.sh; fi'
    #   OSX tvos PURE
    - os: osx
      name: osx-tvos-pure
      osx_image: xcode11.4
      language: java
      jdk: openjdk12
      install: true
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild-pure-tvos.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish-pure-tvos.sh; fi'

    - os: windows
      name: windows-pure
      language: shell
      jdk: openjdk12
      env:
        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
        - JAVA_OPTS=-Xmx2g
        - JDK="adopt-openj9@1.11"
      before_install:
        - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
        - source ~/.install-jdk-travis.sh
      install: true
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then $shell ./windowsBuild-pure.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./windowsBuildAndPublish-pure.sh; fi'
    - os: windows
      name: windows-delegated
      language: shell
      jdk: openjdk12
      env:
        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
        - JAVA_OPTS=-Xmx2g
        - JDK="adopt-openj9@1.11"
      before_install:
        - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
        - source ~/.install-jdk-travis.sh
        - |-
          case $TRAVIS_OS_NAME in
            windows)
              [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
              choco uninstall -y mingw
              choco upgrade --no-progress -y msys2 bazel
              export msys2='cmd //C RefreshEnv.cmd '
              export msys2+='& set MSYS=winsymlinks:nativestrict '
              export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
              export shell="$msys2 -mingw64 -full-path -here -c \$\* --"
              export msys2+=" -msys2 -c \$\* --"
              $msys2 pacman --sync --noconfirm --needed \
                      autoconf \
                      automake \
                      mingw-w64-x86_64-libtool \
                      mingw-w64-x86_64-toolchain \
                      perl \
                      unzip
              taskkill //IM gpg-agent.exe //F
              export CPPFLAGS=-D__USE_MINGW_ANSI_STDIO=1
              export PATH=/C/tools/msys64/mingw64/bin:$PATH
              export GNU_MAKE=mingw32-make
              export MAKE=mingw32-make
              export AR=gcc-ar
              export RANLIB=gcc-ranlib
              export COVERITY_SCAN_BRANCH_PATTERN=disable_coverity_scan
              ;;
          esac
        - export GIT=git
        - g++ --version
        - $GNU_MAKE --version
        - $GIT --version
      install: true
      before_cache:
        - $msys2 pacman --sync --clean --noconfirm
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then $shell ./windowsBuild-delegated.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then $shell ./windowsBuildAndPublish-delegated.sh; fi'
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle
    - $HOME/.konan
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
branches:
  only:
    - master
